CoED = 'COLLEGE OF EDUCATION'
CIVE = 'COLLEGE OF INFORMATICS AND VIRTUAL EDUCATION'
CHAS = 'COLLEGE OF HEALTH AND ALLIED SCIENCES'
SOCIAL = 'COLLEGE OF HUMANITIES AND SOCIAL SCIENCES'
CoES = 'COLLEGE OF EARTH SCIENCES'
college_choices = [(CoED, CoED),
                   (CIVE, CIVE),
                   (CHAS, CHAS),
                   (SOCIAL, SOCIAL),
                   (CoES, CoES),
                   ]
